version: '3'
services:
 
###############################
 cassandra0:
  image: cassandra:3.11.1
  container_name: cassandra0
  ports:
   - 9042:9042
   - 9160:9160
   - 7199:7199
   - 8778:8778
  environment:
   - CASSANDRA_START_RPC=true
  environment:
   - CASSANDRA_SEEDS=cassandra0
   - CASSANDRA_CLUSTER_NAME=mtech_cluster
  ulimits:
    memlock: -1
    nproc: 32768
    nofile: 100000
 
###############################
 cassandra1:
  image: cassandra:3.11.1
  container_name: cassandra1
  ports:
   - 9142:9042
  command: bash -c 'sleep 60;  /docker-entrypoint.sh cassandra -f'
  depends_on:
   - cassandra0
  environment:
   - CASSANDRA_SEEDS=cassandra0
   - CASSANDRA_CLUSTER_NAME=mtech_cluster
  ulimits:
    memlock: -1
    nproc: 32768
    nofile: 100000
 
###############################
 cassandra2:
  image: cassandra:3.11.1
  container_name: cassandra2
  ports:
   - 9242:9042
  command: bash -c 'sleep 120;  /docker-entrypoint.sh cassandra -f'
  depends_on:
    - cassandra0
  environment:
   - CASSANDRA_SEEDS=cassandra0
   - CASSANDRA_CLUSTER_NAME=mtech_cluster
  ulimits:
    memlock: -1
    nproc: 32768
    nofile: 100000
 
 portainer:
  container_name: portainer
  image: portainer/portainer
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  ports:
    - 9000:9000




 psqlprimary:
   hostname: 'primary'
   image: postgres
   environment:
   - PGHOST=/tmp
   - MAX_CONNECTIONS=10
   - MAX_WAL_SENDERS=5
   - PG_MODE=primary
   - PG_PRIMARY_USER=primaryuser
   - PG_PRIMARY_PASSWORD=password
   - PG_DATABASE=testdb
   - PG_USER=testuser
   - PG_PASSWORD=password
   - PG_ROOT_PASSWORD=password
   - PG_PRIMARY_PORT=5432
   volumes:
   - pg-primary-vol:/pgdata
   ports:
   - "5432"
   networks:
   - crunchynet
   deploy:
     placement:
       constraints:
       - node.labels.type == primary
       - node.role == worker
 psqlreplica:
   image: postgres
   environment:
   - PGHOST=/tmp
   - MAX_CONNECTIONS=10
   - MAX_WAL_SENDERS=5
   - PG_MODE=replica
   - PG_PRIMARY_HOST=primary
   - PG_PRIMARY_PORT=5432
   - PG_PRIMARY_USER=primaryuser
   - PG_PRIMARY_PASSWORD=password
   - PG_DATABASE=testdb
   - PG_USER=testuser
   - PG_PASSWORD=password
   - PG_ROOT_PASSWORD=password
   volumes:
   - pg-replica-vol:/pgdata
   ports:
   - "5432"
   networks:
   - crunchynet
   deploy:
     placement:
       constraints:
       - node.labels.type != primary
       - node.role == worker
networks:
  crunchynet:

volumes:
  pg-primary-vol:
  pg-replica-vol:
